AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  PDFtoCSV
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: demo-bmv-konnected-printer-files
  PDFtoCSV:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bmv-sam-code/demo.zip
      Handler: Printer_Job_Parser_v1.lambda_handler::handleRequest
      Runtime: python3.8
      Role: arn:aws:iam::326226458834:role/service-role/demo-function-role-626y4714
      MemorySize: 512
      FileSystemConfigs:
      - Arn: arn:aws:elasticfilesystem:us-east-1:326226458834:access-point/fsap-07c8ececebe135f42
      VpcConfig:
        SecurityGroupIds: 
        - sg-006dc5242aef919a4
        SubnetIds:
        - subnet-01ba1a544ec2d947d
        - subnet-01639cfeedf91da90
      Environment:
        Variables:
          PATH: /mnt/access/jre1.8.0_311/bin/
          PYTHONPATH: /mnt/access/
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref S3Bucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: Unprocessed/
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt PDFtoCSV.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub 'arn:aws:s3:::${S3Bucket}'
